# Generated by Django 4.1.5 on 2023-08-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FruitFarmingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('invest_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('earn_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('per_day_earn', models.DecimalField(decimal_places=2, max_digits=10)),
                ('days', models.IntegerField()),
                ('icon', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
