# Generated by Django 4.1.5 on 2023-08-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitfarmingoption',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
